#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_CONF_INCLUDE_SIMPLE

#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 0

#define LV_TICK_CUSTOM 0
#define LV_SPRINTF_CUSTOM 0
#define LV_MEM_SIZE (128 * 1024)

#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
#define LV_LOG_PRINTF 0

#define LV_USE_DRAW_PBUFFER 1

#endif /* LV_CONF_H */
